---
apiVersion: v2
description: {{cookiecutter.ci_project_title}} Helm Chart
name: {{cookiecutter.ci_project_title}}
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: {{cookiecutter.author}}
    email: {{cookiecutter.email}}
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami