stages:
  - build
  - test
  - deploy_staging
  - deploy_production


variables:
  # for git crypt
  GIT_STRATEGY: clone
  GIT_DEPTH: 1


build_docker_image:
  stage: build
  interruptible: true
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - bin/push "${CI_COMMIT_SHA}" dev
    - bin/push "${CI_COMMIT_SHA}"
    - bin/push latest deploy

test_backend:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/dev:${CI_COMMIT_SHA}"
  needs:
    - build_docker_image
  script:
    - make test_backend_coverage

.deploy:
  image: "${CI_REGISTRY_IMAGE}/deploy:latest"
  cache:
    policy: pull
  before_script:
    - echo $GITCRYPT_SYMETRIC_KEY | base64 -d | tee /tmp/.gitcrypt.key &>/dev/null
    - git-crypt unlock /tmp/.gitcrypt.key
    # You may need to gcloud auth login here
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - helm dependency update ./deploy/chart/
  script:
    - bin/gke.deploy "${CI_COMMIT_SHA}" "${ENV}" $PWD/helm-values.${ENV}.secrets.yaml


deploy_staging:
  extends: .deploy
  stage: deploy_staging
  variables:
    ENV: staging
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy_production:
  stage: deploy_production
  extends: .deploy
  variables:
    ENV: production
  environment:
    name: production
    url: https://{{cookiecutter.production_hostname}}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
