version: '2.1'
services:
  psql:
    image: sameersbn/postgresql:9.6-2
    # ports: ['5432:5432'] # uncomment this to connect from a local desktop sql client
    expose: ["5432"]

    environment:
      DB_NAME: ${CI_PROJECT_NAME}
      DB_PASS: ${CI_PROJECT_NAME}
      DB_USER: ${CI_PROJECT_NAME}
    volumes:
      - /data/${CI_PROJECT_NAME}/postgresql:/var/lib/postgresql

  minio:
    extends:
      service: minio-with-buckets
      file: build.yml
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: test1234
      MINIO_BUCKET: ${CI_PROJECT_NAME}-assets
    #ports: ["9000:9000", "9001:9001"]
    expose: ["9000", "9001"]
    command: minio server /data --console-address ":9001"
    volumes:
      - /data/${CI_PROJECT_NAME}/minio:/data

  django_shell: # This is a one-shot command runner service, for manage.py or bash, it dies immediately
    extends:
      service: ${CI_PROJECT_NAME}-django-dev
      file: build.yml
    volumes:
      - ../:/app
      - ../.pythonrc:/root/.pythonrc
      - ../.pythonhist:/root/.pythonhist
    user: "${UID_GID}"
    links:
      - psql
      - minio
    environment:
      - DJANGO_SETTINGS_MODULE
      - DEVELOP_BACKEND_PORT
      - DATABASE_URL=psql://${CI_PROJECT_NAME}:${CI_PROJECT_NAME}@psql:5432/${CI_PROJECT_NAME}
      - ENV
      - SECRET_KEY=develop_key
      - DEBUG=true
      - SERVICE=django_shell
    command: "bash"
    entrypoint: []

  backend:
    extends:
      service: ${CI_PROJECT_NAME}-django-dev
      file: build.yml
    command: ["/entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "$DEVELOP_BACKEND_PORT:8000"
    links:
      - psql
      - minio
    volumes:
      - ../:/app
    user: "${UID_GID}"
    environment:
      - DJANGO_SETTINGS_MODULE
      - DEVELOP_BACKEND_PORT
      - DATABASE_URL=psql://${CI_PROJECT_NAME}:${CI_PROJECT_NAME}@psql:5432/${CI_PROJECT_NAME}
      - ENV
      - SECRET_KEY=develop_key
      - DEBUG=true
      - SERVICE=backend

  qcluster:
    extends:
      service: ${CI_PROJECT_NAME}-django-dev
      file: build.yml
    command: ["python", "manage.py", "qcluster"]
    links:
      - psql
      - minio
    volumes:
      - ../:/app
    user: "${UID_GID}"
    environment:
      - DJANGO_SETTINGS_MODULE
      - DEVELOP_BACKEND_PORT
      - DATABASE_URL=psql://${CI_PROJECT_NAME}:${CI_PROJECT_NAME}@psql:5432/${CI_PROJECT_NAME}
      - ENV
      - SECRET_KEY=develop_key
      - DEBUG=true
      - SERVICE=qcluster

  frontend:
    extends:
      service: ${CI_PROJECT_NAME}-django-dev
      file: build.yml
    command: "yarn dev"
    entrypoint: []
    working_dir: /app/frontend
    ports:
      - "$DEVELOP_FRONTEND_PORT:3000"
    links:
      - psql
      - minio
    volumes:
      - ../:/app
    user: "${UID_GID}"
    environment:
      - DEVELOP_BACKEND_PORT
      - DEVELOP_FRONTEND_PORT
      - APOLLO_BACKEND_URI=http://backend:8000/api/graphql/
      - NEXT_PUBLIC_APOLLO_URI=http://localhost:$DEVELOP_BACKEND_PORT/api/graphql/
      - ENV
      - DEBUG=true
      - SERVICE=backend

