controllers:
    main:
        replicas: 3
        strategy: RollingUpdate
        containers:
            main:
                command:
                    - /app/infra/prod/start-uvicorn.sh
                image:
                    repository: {{cookiecutter.docker_image_url}}
                env:
                    DATABASE_HOST: postgres-postgresql
                    APP_ENV: staging
                    APP_HOSTNAME: staging.mydomain.com
                probes:
                    liveness:
                        enabled: true
                        port: 8000
                    readiness:
                        enabled: true
                        port: 8000
                    startup:
                        enabled: true
                        port: 8000
service:
    main:
        controller: main
        ports:
            http:
                port: 8000
ingress:
    main:
        className: nginx
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
            - host: staging.mydomain.com
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    name: main
                    port: 8000
        tls:
            - secretName: {{cookiecutter.project_name}}-staging-tls
              hosts:
                - staging.mydomain.com
