version: '2.1'
services:
  psql:
    image: sameersbn/postgresql:9.6-2
#    expose:
#      - '5432'
    ports:
    - "5432:5432"
    environment:
      DB_NAME: ${CI_PROJECT_TITLE}
      DB_PASS: ${CI_PROJECT_TITLE}
      DB_USER: ${CI_PROJECT_TITLE}
    volumes:
      - /data/${CI_PROJECT_TITLE}/production/postgresql:/var/lib/postgresql

  backend:
    extends:
      service: ${CI_PROJECT_TITLE}-backend-django
      file: build.yml
    command: ["/wsgi.sh"]
    ports:
      - "${DEVELOP_BACKEND_PORT}:8000"
    links:
      - psql
    environment:
      - ENV
      - SECRET_KEY
      - SERVICE=runserver
