---
apiVersion: v2
description: {{cookiecutter.ci_project_name}} Helm Chart
name: {{cookiecutter.ci_project_name}}
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: {{cookiecutter.author}}
    email: {{cookiecutter.email}}
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: "12.1.13"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: minio
    version: "5.0.4"
    repository: https://charts.min.io/
    condition: minio.enabled
