name: Deploy to Staging

on:
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
  SOPS_AGE_KEY_FILE: infra-sops-key.txt

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  deploy_staging:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v3
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
    - name: Setup SOPS
      uses: nhedger/setup-sops@v2
    - name: Authenticate to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Decrypt secrets
      run: |
        echo "${{ env.SOPS_AGE_KEY }}" > ${{ env.SOPS_AGE_KEY_FILE }}
        ./bin/sops/unlock-files
    - name: Deploy to staging
      env:
        KUBECONFIG: ./kubeconfig-sa.staging.secrets.yaml
        CI_REGISTRY_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        CI_COMMIT_SHA: ${{ github.sha }}
      run: |
        chmod 0600 ${{ env.KUBECONFIG }}
        helm repo add bjw-s https://bjw-s.github.io/helm-charts
        ./bin/helm-deploy ${{ github.sha }} staging
